id: P000134
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །ཐེག་པ་ཆེན་པོའི་གདམས་ངག་བློ་སྦྱོང་དོན་བདུན་མ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། སྒ་རབ་འབྱམས་པ་ཀུན་དགའ་ཡེ་ཤེས།
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - sabche
  id: IBA-MT-05-1
web_metadata:
  title:
    en: A Stream of Nectar:Instructions for Meditation on the Two Bodhichittas
    bo: བྱང་ཆུབ་ཀྱི་སེམས་གཉིས་སྒོམ་པའི་མན་ངག་བདུད་རྩིའི་ཆུ་རྒྱུན།
  collection:
    en: IBA Mind Training Series–  Book 5
    bo: རྒྱལ་ཡོངས་གསུང་རབ་བློ་སྦྱོང་བསྟར་རིམ།–  དེབ། ༥
  author:
    en: Garab Jampa Kunga Yeshe
    bo: སྒ་རབ་འབྱམས་པ་ཀུན་དགའ་ཡེ་ཤེས།
  pusblisher:
    en: IBA Publications
    bo: རྒྱལ་ཡོངས་གསུང་རབ་སློབ་གཉེར་ཁང་།
  sku: IBA-MT-05-1
  category:
    en: Bodhichitta
    bo: བྱང་ཆུབ་ཀྱི་སེམས།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: IBA-MT-05-1.epub
  description:
    en: This contains the practical instruction on how to meditate on the two awakening
      minds.
    bo: བྱང་ཆུབ་སེམས་དཔའི་ཉམས་ལེན་སྐོར།
